### ISSUE TITLE
请问怎么关闭web终端RDP VNC远程桌面右侧工具栏

### ISSUE THREAD

**Issue by kangseung** [jumpserver/lion-release#1]
请问怎么关闭web终端RDP VNC远程桌面右侧工具栏

总是挡住窗口关闭按钮和右下角时间按钮，鼠标向右移动碰到还自动放大，基本没法用了

**Comment by ibuler** [comment]
马上发布修复版本

**Comment by ibuler** [comment]
v2.10.2 已修复，点击才会展开

**Comment by kangseung** [comment]
前一阵子装了最新版本 发现右边那个条还在呀 ， 具体咋关闭呢

**Comment by LeeEirc** [comment]
右侧栏目前会一直存在，只是会展开和折叠。
