### ISSUE TITLE
[Question] 需要源码

### ISSUE THREAD

**Issue by rayPan2333** [jumpserver/lion-release#3]
**请描述您的需求或者改进建议.**
考虑到已经是重要组件之一，lion只有release二进制，不知道是否遵循GPL2.0，希望尽快有源码可以放出供参考学习

**Comment by ibuler** [comment]
内部讨论中，等待企业版有更强功能后会逐步放开，另外 lion license 不是 GPL

**Comment by seaurching** [comment]
我也需要源码，在做第三方系统适配呢。能够给个源码。看你们官方提供了amd和ppc，我在做mips64小端的适配
